[project]
name = "mnemonic-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bip-utils>=2.9.3",
    "pycardano>=0.15.0",
]
